#!/bin/bash

if [ "$#" == "0" ]; then
    emacsclient -c -e "(my-dired-frame default-directory)"
fi

if [ "$#" == "1" ]; then
    emacsclient -c -e "(my-dired-frame \"$1\")"
fi

if [ "$#" == "2" ]; then
    emacsclient -c -e "(my-dired-frame \"$1\" \"$2\")"
fi
